export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO'

//state para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'

export const CONFIRMAR_ORDENAR_PLATILLOS = 'CONFIRMAR_ORDENAR_PLATILLOS'

export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'

export const CONTINUAR_PEDIDO = 'CONTINUAR_PEDIDO'
export const LIMPIAR_TODO= 'LIMPIAR_TODO'